name: Data Preprocessing Pipeline

# Trigger: Jalan otomatis saat push ke branch main
# Terutama jika ada perubahan di data mentah atau script python
on:
  push:
    branches:
      - main
    paths:
      - 'namadataset/**'
      - 'preprocessing/automate_surya.py'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_surya.py \
            --input "datasets/heart_disease.csv" \
            --output "preprocessing/heart_disease_preprocessing"

      - name: Commit and Push Processed Data
        run: |
          # Konfigurasi identitas bot git
          git config --global user.name "rafli21xrplc"
          git config --global user.email "raflisurya824@github.com"
          
          # Tambahkan file hasil preprocessing ke staging area
          git add preprocessing/heart_disease_preprocessing/train.csv
          git add preprocessing/heart_disease_preprocessing/test.csv
          
          # Commit perubahan (jika ada data baru/berubah)
          # "|| echo..." mencegah error jika hasil sama persis (tidak ada perubahan)
          git commit -m "Auto-update processed dataset by GitHub Actions" || echo "No changes to commit"
          
          # Push kembali ke repository
          git push
